#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import requests
import bs4
import time

headers = {
	'User-Agent':'Mozilla/5.0(X11;Ubuntu;Linux x86_64;rv:62.0)Gecko/20100101 Firefox/62.0'
}

with requests.Session() as s:
	req=s.get('https://github.com/login', headers=headers)
	soup = bs4.BeautifulSoup(req.text,'html5lib')
	token = soup.find("input", {"name": "authenticity_token"}).attrs['value']
	commit = soup.find("input", {"name": "commit"}).attrs['value']        

	payload = {
	'authenticity_token': token,
	'commit': commit,
	'login':'samyak360',
	'password':'set2hisamyak'
	}

	r = s.post('https://github.com/session', data=payload, headers=headers)
	soup = bs4.BeautifulSoup(r.text,'lxml')
	repo = soup.select('.f5.dashboard-underlined-link span')
	counter=1
	for i in repo:
		if(counter%2!=0):
			print "# : ",i.text+"/",
		else:
			print i.text
			time.sleep(1)
		counter+=1
