print("Johny Johny yes papa")
print("	eating sugar no papa ")
print("		telling lie no papa")
print("		open ur mouth ha ha ha ")
print("Twinkle, twinkle, little star, ")
print("	How I wonder what you are")